In [1]:
import numpy as np


In [2]:
arr = np.arange(0, 16)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr = arr.reshape(4,4)

In [5]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
arr = arr.reshape(1,4,4,1)
arr.shape

(1, 4, 4, 1)

In [7]:
arr

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14],
         [15]]]])

In [8]:
type(arr)


numpy.ndarray

In [9]:
arr1 = np.arange(1, 26)

In [10]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [11]:
arr1 = arr1.reshape(1,5,5,1)

In [12]:
#arr1

In [18]:
import numpy as np

a = np.diag((1, 2, 3))
 
print("Array is :",a)
 
c, d = np.linalg.eig(a)
 
print("Eigen value is :",c)

print("Eigen value is :",d)

Array is : [[1 0 0]
 [0 2 0]
 [0 0 3]]
Eigen value is : [1. 2. 3.]
Eigen value is : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
